# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.
"heroes" = "󱡮 "
"steam" = "󰓓 "
"mail" = " "
"kitty" = ""
"obsidian" = " "
"blue" = ""
"pavucontrol" = "󰕾 "
".pdf" = ""
"relay" = "󰢹 "
"code" = "󰨞"
"github" = ""
"rust" = ""
"telegram" = ""
"gimp" = ""
"caja" = ""
"private browsing" = ""
"spotify" = ""
"teams" = "󰊻 "
"font" = ""
"firefox" = ""
"rstudio" = "R"
"intellij" = ""
"clion" = ""
"chromium" = ""
"pcmanfm" = " "
"nvim" = ""
"gthumb" = " "
"transmission" = " "
"music" = " "

[other]
fallback_icon = "_"
deduplicate_icons = false
